// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM7YdHieZB-xu3hQLKvxGBFkzY1_h4atg',
    appId: '1:51607476551:web:69e4f02e3c81ea775dd462',
    messagingSenderId: '51607476551',
    projectId: 'shopping-app-84439',
    authDomain: 'shopping-app-84439.firebaseapp.com',
    storageBucket: 'shopping-app-84439.firebasestorage.app',
    measurementId: 'G-DR3JP5RL1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLuILAZIDTIAgHpas14s48zf_JnL8eYzo',
    appId: '1:51607476551:android:8f5e11b6b2923b8a5dd462',
    messagingSenderId: '51607476551',
    projectId: 'shopping-app-84439',
    storageBucket: 'shopping-app-84439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqE2UuTMQ2pF5K7LZHvIPh7tWtSBb9oKk',
    appId: '1:51607476551:ios:ae055c8aa4e678815dd462',
    messagingSenderId: '51607476551',
    projectId: 'shopping-app-84439',
    storageBucket: 'shopping-app-84439.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqE2UuTMQ2pF5K7LZHvIPh7tWtSBb9oKk',
    appId: '1:51607476551:ios:ae055c8aa4e678815dd462',
    messagingSenderId: '51607476551',
    projectId: 'shopping-app-84439',
    storageBucket: 'shopping-app-84439.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM7YdHieZB-xu3hQLKvxGBFkzY1_h4atg',
    appId: '1:51607476551:web:c1d2d0047627a6315dd462',
    messagingSenderId: '51607476551',
    projectId: 'shopping-app-84439',
    authDomain: 'shopping-app-84439.firebaseapp.com',
    storageBucket: 'shopping-app-84439.firebasestorage.app',
    measurementId: 'G-7H19GDPRDK',
  );
}
